import Head from 'next/head'
import Image from 'next/image'
import Header from '../components/Header'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className="text-3xl">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <Header/>
      <main className='pt-16 w-full'>
          <section className='min-h-[300px] max-h-[360px] w-full bg-darkblue'>
              <div className='min-h-[300px] max-h-[360px] w-full flex items-center'>
                  <div className='p-5 lg:px-10 lg:py-8 w-full'>
                      <div className='text-white mb-5'>
                        <h2 className='text-5xl font-bold '>Welcome</h2>
                        <h3 className='text-3xl font-semibold'>Millions of movies, TV shows and people to discover. Explore now.</h3>
                      </div>

                      <div className='w-full relative'>
                        <form className='w-full'>
                              <input className='w-full h-12 text-lg border-none rounded-3xl outline-none py-2 px-5'/>
                              <input type='submit' value='Search' className='absolute text-base font-bold text-white px-6 py-2 rounded-full bg-lightblue h-12 right-[-1px] top-0'/>
                        </form>
                      </div>
                  </div>
              </div>
          </section>
      </main>
      
    </div>
  )
}
